### ISSUE TITLE
Proposal to rename `getUserAccountBalance()` to `getUserUnallocatedCollateralBalance()`

### ISSUE THREAD

**Issue by perfectmak** [MARKETProtocol/MARKET.js#127]
### User Story

As a user of the MarketJS library, I would prefer if `MarketJS.getUserAccountBalance()` was renamed to another function like `MarketJS. getUserUnallocatedCollateralBalance()`

### Why Is this Needed?

This is needed because the name `getUserAccountBalance()` implies that we are getting the account balance of a user participating in the contract, but doesn't show clearly that we are indeed checking the balance of collateral the user has deposited into the collateral pool for the contract.

### Description

*Type*: Feature

### Current Behavior

`MarketJS.getUserAccountBalance(mktContractAddress: string, userAddress :string)`

### Expected Behavior

`MarketJS. getUserUnallocatedCollateralBalance(mktContractAddress: string, userAddress: string)`

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: `getUserAccountBalance()` should be renamed to `getUserUnallocatedCollateralBalance()` in the MarketJS library.

**Comment by pelsasser** [comment]
@perfectmak - Yes, I have struggled with this one myself.  Whatever naming we decide on should start in the solidity code itself.  Here is the current explanation for the names, we can certainly refactor the solidity and then marketjs if we all agree on a clearer naming structure.

A user deposits tokens for trading to a specific contract, in the solidity this is all referred to as the `UserAccount` once they execute a trade, the funds get "moved" from the `UserAccount` to the shared `collateralPoolBalance` for that contract, and are locked until the user exits a position or the contract expires.

Your suggestion is to call the `UserAccount` the `CollateralPool` itself, which I understand.  Originally, I decided that since those funds weren't yet really part of the collateral pool (not committed to a trade) that it was confusing to go with the naming convention your describing.  I could be totally misguided in this, as maybe it is causing more confusion than its worth.

@MARKETProtocol/core - any more thoughts on this?
@cryptomental - want to offer an opinion?

**Comment by eswarasai** [comment]
@pelsasser -- I just went through the CollateralPool Smart Contract just to make sure I understand the above comment. I don't think we're keeping track of the current balance of the user in the shared collateral pool, so it doesn't make sense to call `getUserCollateralPoolBalance()`. On the other hand, `getUserAccountBalance()` isn't self explanatory. Ideally, this function should be `getUserUnallocatedBalance()`. Let me know if this makes sense. Thanks!

**Comment by perfectmak** [comment]
@pelsasser I understand your point, but the `UserAccount` is not self-explanatory unless collateral is put into context somewhere. For the solidity code, it is a little explanatory because the function is attached to the MarketCollateralPool contract, but I think @eswarasai suggestion about a name like `getUserUnallocatedBalance()` would make it even more intuitive.

Now for the MarketJS function, @eswarasai what if we name it `getUserUnallocatedCollateralBalance()` in marketjs, it sounds quite verbose but I still feel this way we might have more clarity on the MarketJS side from users and I don't think we would need to update the solidity code @pelsasser.

**Comment by eswarasai** [comment]
@perfectmak -- Yeah, that works too 👍 Will await for confirmation from @pelsasser

**Comment by travisdmathis** [comment]
@eswarasai @perfectmak this could include also adding the `getUserWalletTokenBalance` function that we want to add to `MARKET.js`

I also agree that this function needs to be renamed as there has been quite a bit of confusion around it the past couple weeks.

**Comment by perfectmak** [comment]
@travisdmathis About the `getUserWalletTokenBalance()` function, this was discussed over #128.
And it has been resolved. The function was just named `getBalanceAsync()` instead. Please take a look.

Since this method might be getting a name change, I believe `getBalanceAsync()` should not be okay instead of `getUserWallerTokenBalance()`.

**Comment by pelsasser** [comment]
`getUserUnallocatedCollateralBalance` works for me.

**Comment by perfectmak** [comment]
Okay, so I'll rename and update the description of this issue to `getUserUnallocatedCollateralBalance`. Then I believe we can create another issue in the contracts repository to handle the changes there too. Is this okay?

**Comment by pelsasser** [comment]
@perfectmak - contracts repo meaning MARKETProtocol/MARKETProtocol?

**Comment by perfectmak** [comment]
@pelsasser it is okay to proceed with this changes right?

**Comment by pelsasser** [comment]
@perfectmak - yes
