### ISSUE TITLE
[API] Convert getOrderHash() and isValidSignatureAsync() to static methods in `MARKET.js`

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/MARKET.js#163]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a developer, I want the ability to call getOrderHash() and isValidSignatureAsync() statically so that I reduce the dependency on web3.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Remove the dependency on web3 to help make unit testing simpler.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
Requires web3 to use getOrderHash() and isValidSignatureAsync()

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Eliminate the need for web3 as a dependency for getOrderHash() and isValidSignatureAsync()

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Allow getOrderHash() and isValidSignatureAsync() to be called as static methods.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- Call getOrderHash() and isValidSignatureAsync() as static methods
- All tests pass

**Comment by perfectmak** [comment]
@rojosnow, I have a little comment on this: getOrderHash() can be easily be moved to be a static method, since it doesn't have dependencies on web3, but for `isValidSignatureAsync()` we would have to expose a non-async version if we don't want to depend on web3. We actually have a none async check in the assertions library `assert.isValidSignature()`.

So I believe this issue should be updated to exposing the non-async `isValidSignature()` function as a static function on MarketJS.

And I also propose that we leave the non static `isValidSignatureAsync()` or maybe keep it internal, so we use in tests just to always ensure our off-chain hashing functions are still in sync with the on-chain one.

cc @pelsasser

**Comment by rojosnow** [comment]
@perfectmak @pelsasser Just to be clear, I'm ok leaving the async version of these functions if they are useful.
