### ISSUE TITLE
[Git] Discuss removal of slow pre-commit hooks 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKET.js#32]
## Cons: 

- Slow
- Currently must be bypassed due to failing coverage percents
- Encourages people to call with --no-verify, negating any benefits
- Testing is better done upon PR's or before merging

## Pros:
?
cc @eswarasai @rojosnow  any thoughts on this.  I personally do not like the pre-commit hook testing workflow.

**Comment by rojosnow** [comment]
Once the work is completed...defined as a PR, it needs to be tested and documented per the guidelines we put out there. When work is in progress, it's best to have some flexibility esp. due to the range of developers we work with.

I'd say we have a script for `pre-pr` that has to pass in order to for a PR to be created. Along the way, if a commit is broken or test coverage is lacking or whatever, have the developer call that out in the issue and/or commit message. A lot of times, it's good to get code on the server for others to pull down and take a look at. In those cases, the `pre-commit` stuff gets in the way.

I'd vote for revising our workflow and documenting the need to test and lint along the way using the scripts we provide. Then, before a PR, the code must pass the `pre-commit` scripts we identify. I don't think there is a lot of work here other than documenting the change in the contribution guidelines.

**Comment by pelsasser** [comment]
@rojosnow - agreed.

Travis can take care of all the needed testing before a PR. Will let @eswarasai weigh in, but I say kill the pre-commit!

**Comment by eswarasai** [comment]
I agree with the Cons but the current phase is just temporary where we're consistently seeing failing pre-commit hooks due to less coverage.

The whole idea behind `pre-commit` hooks running `npm run build && npm run test` along with linting is to avoid pushing of failing builds as well as any failing test cases due to changes in the code. I personally don't want to wait till Travis CI build throws an error.

PR is just one scenario where external contributors are contributing and we'd very much like to run the entire test suite. But there can be scenarios where we'd be committing the changes directly on `develop` in which case there might not always be a PR workflow to rely upon running the tests.

All the other repos like `dApp` and `website` have the same `pre-commit` hooks and those have been updated from the time to make it ease for us to review.

Solution: For the time being, we can comment the `globalCoverageThreshold` from `MARKET.js` and `types` `package.json` file so that the tests will pass along with the `pre-commit` hooks.

Not really sure how can we fix the slow running tests but I personally am against removing the `pre-commit` hooks because in case the build fails or a test case fails due to the code changes, I'd very much like to know them before committing, so that I can fix them and I feel `pre-commit` hooks are the only place where these checks are needed to pass. Let me know if you disagree. Thanks!

**Comment by rojosnow** [comment]
To clarify, I'm not suggesting we remove the functionality. I think it's important. The question for me is, what are the use cases for our workflow and where should we automatically run `pre-commit` scripts? One use case is a PR, another is committing changes directly to `develop`, another is incremental commits as you work on the code, and the last is committing incomplete code to get something checked in or another set of eyes on it. Any more you guys can think of?

I think we need a workflow that accommodates our use cases. A majority of my work falls into incremental commits and getting code checked in. PRs and changes directly to branches are more infrequent. I find I'm using `--no-verify` a good bit to save time when I'm coding. So, I'd prefer to opt-in to `pre-commit` required or needed. I think we're all in agreement about the scripts...it's just about the default behavior.

**Comment by pelsasser** [comment]
I like opt-in functionality personally for commits that way if @eswarasai wants to run tests before *every* commit he can, but if @rojosnow doesn't want to, he doesn't have to.

**Comment by eswarasai** [comment]
@pelsasser -- Any suggestion you have on how to implement opt-in for pre-commit hooks? The whole idea of having pre-commit hooks is to pass all the checks and push clean code to the GitHub. If someone wants to opt-in the hooks, the only option is to add `--no-verify` param to `git commit`. So let me know what we have concluded here. Thanks!

**Comment by pelsasser** [comment]
opt in model is for testing.  

IE you have the option of running
```
npm run build
npm run test
npm run lint
```

etc... before committing, but no hook to enforce it.

**Comment by eswarasai** [comment]
@pelsasser -- Sure. I can ignore `build` and `tests` commands in `pre-commit` hooks but not the `lint` as it's mandatory to follow the defined code styling. But before doing that, I'd like to confirm if we're going to strictly follow the PR process for merging all the commits to `develop` using `release`, `feature` and `hotfix` branches so that we can verify that Travis CI build is passed before merging any commit. Let me know if this is the decided workflow.

**Comment by pelsasser** [comment]
okay so lets leave the linting hook and remove the rest.

100% on board for gitflow. It has been working well for me.

**Comment by rojosnow** [comment]
@eswarasai Are you talking about the process or the helper commands? As far as the process, merging/rebasing a feature branch into develop with a PR seems to be ok, no??

**Comment by eswarasai** [comment]
@rojosnow -- I was referring to the `git-flow` command line tool. Since we're taking the PR approach, there's no need for us to use the `git-flow` tool going forward.
